name: PHP Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"

    - name: Install Dependencies
      run: composer install

    - name: Install PHP_CodeSniffer
      run: composer require squizlabs/php_codesniffer --dev
  
    - name: Run PHP Code Sniffer
      run: vendor/bin/phpcs

    - name: Run PHP Mess Detector
      run: vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

    - name: Deploy to Production
      run: |
        if [ ${{ github.ref }} = 'refs/heads/main' ]; then
          echo "Deploying to production..."
          # Add your deployment steps here
        fi

